version: '3.1'

services:

  db:
    image: mysql:8.0.28
    container_name: my_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
    - $HOME/workspace/docker/mysql/db/data:/var/lib/mysql
    - $HOME/workspace/docker/mysql/db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
    - 13306:3306