version: '3.1'

services:

  db:
    image: mongo:latest
    container_name: my_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    volumes:
    - $HOME/workspace/docker/mongo/data/db:/data/db
    - $HOME/workspace/docker/mongo/data/configdb:/data/configdb
    ports:
    - 28001:27017